# Netlify Configuration File

[build]
  # Vite builds the final static site into the 'dist' folder
  publish = "dist"
  command = "npm run build"

# Single Page Application (SPA) Routing Rewrite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
